# -*- coding: utf-8 -*-
"""19CSR036 ASSIGNMENT_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1i_Z21DdBpjIpHScONBDv_1hk1U1mRbqO
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
#from tensorflow.keras.preprocessing.image import image
import numpy as np
from keras.models import Sequential
from keras.layers import Conv2D,Dense, Flatten, MaxPool2D,Dropout
#IMAGE augumentation
gen=ImageDataGenerator(
    rotation_range=0.2,
    rescale=1/255.0,
    zoom_range=0.05,
    width_shift_range=0.05,
    height_shift_range=0.05,
    shear_range=0.05,
    horizontal_flip=True,
    fill_mode="nearest"
)
train_generator = gen.flow_from_directory(
"C:\\Users\\Vetri\\Downloads\\Flowers-Dataset\\flowers",
	target_size=(64,64),
	class_mode='categorical',
  batch_size=30
)
#CREATING A MODEL
model = Sequential([
    Conv2D(64, (3,3), activation='relu',input_shape=(64,64,3)),
    MaxPool2D(2, 2),
    Conv2D(64, (3,3), activation='relu'),
    MaxPool2D(2,2),
    Flatten(),
    Dropout(0.5),
    Dense(512, activation='relu'),
    Dense(5, activation='softmax')
])
#COMPILE THE MODEL
model.compile(loss = 'categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
#FIT THE MODEL TO TRAIN DATASET
history = model.fit(train_generator, epochs=25, steps_per_epoch=25, verbose = 1, validation_steps=3)

from keras import models #SAVING MODEL AND PREDICTING RESULT WITH THE SAVED MODEL
from keras.models import load_model
from keras.preprocessing import image
from keras.utils import img_to_array, load_img
from keras.utils.image_dataset import load_image
model.save("mod.h5")
md=load_model("C:\\Users\\Vetri\\Downloads\\Flowers-Dataset\\flowers\\mod.h5")
img=load_img("C:\\Users\\Vetri\\Downloads\\Flowers-Dataset\\flowers\\rose\\12240303_80d87f77a3_n.jpg",target_size=(64,64))
x=img_to_array(img)
x=np.expand_dims(x,axis=0)

r=md.predict(x)

labels=["daisy"," dandelion","rose","sunflower","tulip"]
y=np.argmax(r)
labels[y]